quarkus:
  profile: local
  http:
    port: 8082
app:
  api-key: ${API_KEY}
  jwt:
    jwt-key: ${JWT_KEY}
  paypal:
    base-url: ${PAYPAL_URL}
    client-id: ${PAYPAL_CLIENT_ID}
    client-secret: ${PAYPAL_CLIENT_SECRET}