quarkus:
  rest-client:
    paypal:
      url: ${PAYPAL_URL}
      verify-host: true
    user:
      url: ${BASE_SERVICE_URL}
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DATABASE_URL}
      max-size: 16
  hibernate-orm:
    database:
      default-catalog: update
    log:
      sql: true
      format-sql: true
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
      color: false